cmake_minimum_required(VERSION 3.5.X)


set(CMAKE_CXX_STANDARD 20)

set(SERVER_MANAGER_BINARY_NAME "L-Type-ServerManager")

project(${SERVER_MANAGER_BINARY_NAME} LANGUAGES CXX)

set(SERVER_MANAGER_FOLDER app/ServerManager)

set(INCLUDE_SERVER_MANAGER ${SERVER_MANAGER_FOLDER}/include)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${SERVER_MANAGER_FOLDER})

file(READ ${SERVER_MANAGER_FOLDER}/src.txt SOURCE_FILES_CONTENT_SERVER_MANAGER)

string(REPLACE "\n" ";" SOURCE_FILES_SERVER_MANAGER ${SOURCE_FILES_CONTENT_SERVER_MANAGER})

add_executable(${SERVER_MANAGER_BINARY_NAME} ${SOURCE_FILES_SERVER_MANAGER})

target_include_directories(${SERVER_MANAGER_BINARY_NAME} PUBLIC ${INCLUDE_SERVER_MANAGER})
