cmake_minimum_required(VERSION 3.27.7)

set(CMAKE_CXX_STANDARD 20)

set(GRAPHIC_MANAGER_BINARY_NAME "R-Touhou-GraphicManager")

project(${GRAPHIC_MANAGER_BINARY_NAME} LANGUAGES CXX)

set(GRAPHIC_MANAGER_FOLDER engine/GraphicManager)

set(INCLUDE_GRAPHIC_MANAGER ${GRAPHIC_MANAGER_FOLDER}/include)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${GRAPHIC_MANAGER_FOLDER})

file(READ ${GRAPHIC_MANAGER_FOLDER}/src.txt SOURCE_FILES_CONTENT_GRAPHIC_MANAGER)

string(REPLACE "\n" ";" SOURCE_FILES_GRAPHIC_MANAGER ${SOURCE_FILES_CONTENT_GRAPHIC_MANAGER})

add_executable(${GRAPHIC_MANAGER_BINARY_NAME} ${SOURCE_FILES_GRAPHIC_MANAGER})

target_include_directories(${GRAPHIC_MANAGER_BINARY_NAME} PUBLIC ${INCLUDE_GRAPHIC_MANAGER})
