cmake_minimum_required(VERSION 3.27.7)

set(CMAKE_CXX_STANDARD 20)

set(L_TYPE_BINARY_NAME "L-Type")

project(${L_TYPE_BINARY_NAME} LANGUAGES CXX)

set(L_TYPE_FOLDER app/Instance)

set(INCLUDE_L_TYPE ${L_TYPE_FOLDER}/include)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${L_TYPE_FOLDER})

file(READ ${L_TYPE_FOLDER}/src.txt SOURCE_FILES_CONTENT_L_TYPE)

string(REPLACE "\n" ";" SOURCE_FILES_L_TYPE ${SOURCE_FILES_CONTENT_L_TYPE})

add_executable(${L_TYPE_BINARY_NAME} ${SOURCE_FILES_L_TYPE})

target_include_directories(${L_TYPE_BINARY_NAME} PUBLIC ${INCLUDE_L_TYPE})
