cmake_minimum_required(VERSION 3.27.7)

set(CMAKE_CXX_STANDARD 20)

set(SERVER_MANAGER_BINARY_NAME "L-Type")

project(${INSTANCE_BINARY_NAME} LANGUAGES CXX)

set(INSTANCE_FOLDER app/Instance)

set(INCLUDE_INSTANCE ${INSTANCE_FOLDER}/include)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${INSTANCE_FOLDER})

file(READ ${INSTANCE_FOLDER}/src.txt SOURCE_FILES_CONTENT_INSTANCE)

string(REPLACE "\n" ";" SOURCE_FILES_INSTANCE ${SOURCE_FILES_CONTENT_INSTANCE})

add_executable(${INSTANCE_BINARY_NAME} ${SOURCE_FILES_INSTANCE})

target_include_directories(${INSTANCE_BINARY_NAME} PUBLIC ${INCLUDE_INSTANCE})
