cmake_minimum_required(VERSION 3.27.7)

set(CMAKE_CXX_STANDARD 20)

set(ROOM_MANAGER_BINARY_NAME "R-Touhou-Room-Manager")

project(${ROOM_MANAGER_BINARY_NAME} LANGUAGES CXX)

set(ROOM_MANAGER_FOLDER engine/RoomManager)

set(INCLUDE_ROOM_MANAGER ${ROOM_MANAGER_FOLDER}/include)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${ROOM_MANAGER_FOLDER})

file(READ ${ROOM_MANAGER_FOLDER}/src.txt SOURCE_FILES_CONTENT_ROOM_MANAGER)

string(REPLACE "\n" ";" SOURCE_FILES_ROOM_MANAGER ${SOURCE_FILES_CONTENT_ROOM_MANAGER})

add_executable(${ROOM_MANAGER_BINARY_NAME} ${SOURCE_FILES_ROOM_MANAGER})

target_include_directories(${ROOM_MANAGER_BINARY_NAME} PUBLIC ${INCLUDE_ROOM_MANAGER})
