cmake_minimum_required(VERSION 3.27.7)

set(CMAKE_CXX_STANDARD 20)

set(CLIENT_MANAGER_BINARY_NAME "R-Touhou-Client-Manager")

project(${CLIENT_MANAGER_BINARY_NAME} LANGUAGES CXX)

set(CLIENT_MANAGER_FOLDER engine/ClientManager)

set(INCLUDE_CLIENT_MANAGER ${CLIENT_MANAGER_FOLDER}/include)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/${CLIENT_MANAGER_FOLDER})

file(READ ${CLIENT_MANAGER_FOLDER}/src.txt SOURCE_FILES_CONTENT_CLIENT_MANAGER)

string(REPLACE "\n" ";" SOURCE_FILES_CLIENT_MANAGER ${SOURCE_FILES_CONTENT_CLIENT_MANAGER})

add_executable(${CLIENT_MANAGER_BINARY_NAME} ${SOURCE_FILES_CLIENT_MANAGER})

target_include_directories(${CLIENT_MANAGER_BINARY_NAME} PUBLIC ${INCLUDE_CLIENT_MANAGER})
